global:
  resolve_timeout: 10s

route:
  receiver: 'pager'
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 1m
  group_by: [ alertname ]

receivers:
  - name: 'pager'
    webhook_configs:
      - url: "http://webhook-listener:8080/"
        send_resolved: true

