# TODO: do something to validate all the colors!

- name: AlertManagerAlert
  channel: 0
  color: red

# *Error: red
# *CalendarEvent: blue
# *BuildFailure: purple

- name: PersonalCalendarError
  channel: 1
  color: red
- name: PersonalCalendarEvent
  channel: 1
  color: bue

- name: DigitalEdCalendarError
  channel: 2
  color: red
- name: DigitalEdCalendarEvent
  channel: 2
  color: blue
- name: DigitalEdBuildFailure
  channel: 2
  color: purple

- name: MaplesoftCalendarError
  channel: 3
  color: red
- name: MaplesoftCalendarEvent
  channel: 3
  color: blue


- name: DebugRed
  channel: 4
  color: red
- name: DebugGreen
  channel: 5
  color: green
- name: DebugBlue
  channel: 6
  color: blue
