global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'everything'
    static_configs:
      - targets:
        - "172.17.0.1:9323"
        - "alertmanager:9093"
        - "bitbucket:9000"
        - "calendar-listener:9000"
        - "cadvisor:8080"
        - "grafana:3000"
        - "led-controller:9000"
        - "loki:3100"
        - "outlook-listener:9000"
        - "prometheus:9090"
        - "promtail:9080"
        - "webhook-listener:9000"
        # TODO: monitor nginx?

rule_files:
    - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
